version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking-service-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      SECRET_KEY: "hZyoyplflKGLIHaOjLC/JMsQdJwkTy6nbfu4h4KoHHec9Q8+jvwqP/jg+E+F3QXE"
    ports:
      - "8080:8080"
    command: ["java", "-jar", "app.jar"]

volumes:
  postgres-data:
    driver: local
